version: '3'
services:
  webapi:
    image: eclipse-works:latest
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - MongoDb__ConnectionString=mongodb://db:27017
      - MongoDb__DatabaseName=eclipse_works
    ports:
      - "8080:8080"
    networks:
      - app_network
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: db
    ports:
      - "27017:27017"
    environment:
      - name=mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data: {}
    
networks:
  app_network:
    driver: bridge